from pydantic import BaseModel, validator
#These are the pydantic models/schemas used in the API

class Pokemon(BaseModel):
    
    id: int #(id is autogenerated so we can remove it)
    title: str
    description: str

    #@validator("title") #request and the next is a response function
    #def title_must_be_min_3_characters(cls, v): #cls and value
        #if len(v) < 3:
            #raise ValueError("Title must be at least 3 characters long!")
        #return v
#get the response to also include id, so now we have, title, description and id = this new class extends the previous class    
#response model for Pokemon
class PokemonResponseModel(Pokemon):
    id: int

    class Config():
        orm_mode = True

class PokemonStats(BaseModel):
    title: str
    description: str

#response model for PokemonStats
class PokemonStatsRepsonseModel(PokemonStats):
    id: int
    class Config():
        orm_mode = True